name: security-action
on: [push]
jobs:   
  Veracode-Software-Composition-Analisys:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      env:
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: |
        curl -sSL 'https://download.sourceclear.com/ci.sh' | bash -s - scan --update-advisor --pull-request

  Veracode-SAST-Pipeline-Scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'veracode.zip'
        path: .
    - uses: actions/setup-java@v3   
      with:
       distribution: 'zulu' # See 'Supported distributions' for available options
       java-version: '8'
    - uses: actions/upload-artifact@v2 
      with:
        path: veracode.zip
    - name: Download the Pipeline Scanner
      uses: wei/curl@master
      with:
        args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
    - name: Unzip the Pipeline Scanner
      run: unzip -qq -n pipeline-scan-LATEST.zip
    - shell: bash
      run: |
        java -jar pipeline-scan.jar --veracode_api_id "${{ secrets.VERACODE_ID }}" --veracode_api_key "${{ secrets.VERACODE_KEY }}" --file "veracode.zip" --issue_details true
  
  Veracode-SAST-Policy-Scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'veracode.zip'
        path: .
     
    - uses: actions/setup-java@v3
    
      with:
       distribution: 'zulu' # See 'Supported distributions' for available options
       java-version: '8'
              
    - uses: actions/upload-artifact@v2 
      with:
        path: NodeGoat/veracode.zip 
    - uses: veracode/veracode-uploadandscan-action@master 
      with:
        vid: '${{ secrets.VERACODE_ID }}'
        vkey: '${{ secrets.VERACODE_KEY }}'
        criticality: 'VeryHigh'
        appname: 'NodeGoat-Furia'
        createprofile: 'true'
        filepath: 'veracode.zip'
        deleteIncompleteScan: 'true'
        version: ${{ github.run_id }}'
        scantimeout: 30
