name: security-action
on: [push]
jobs:   
  Veracode-SAST-Policy-Scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'veracode.zip'
        path: .
     
    - uses: actions/setup-java@v3
    
      with:
       distribution: 'zulu' # See 'Supported distributions' for available options
       java-version: '8'
        
      
    - uses: actions/upload-artifact@v2 
      with:
        path: NodeGoat/veracode.zip 

    - uses: veracode/veracode-uploadandscan-action@master 
      with:
        vid: '${{ secrets.VERACODE_ID }}'
        vkey: '${{ secrets.VERACODE_KEY }}'
        criticality: 'VeryHigh'
        appname: 'Node-Vulnerable-Demo'
        createprofile: 'true'
        filepath: 'veracode.zip'
        deleteIncompleteScan: 'true'
        version: ${{ github.run_id }}'
        scantimeout: 30
        
  Veracode-SAST-Pipeline-scan:
  - name: Veracode Pipeline-Scan
  uses: veracode/Veracode-pipeline-scan-action@pipeline-scan-beta-v0.0.4
  with:
        vid: '${{ secrets.VERACODE_ID }}'
        vkey: '${{ secrets.VERACODE_KEY }}'
    file: veracode.zip
